using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlamePlanner
{
    /// <summary>
    /// This class provides TEMPLATES for several events.
    /// </summary>
    public static class AllEvents
    {
        public static EventObject EricNam = new EventObject()
            .SetEventName("Eric Nam Before We Begin World Tour")
            .SetImage(new Uri("EricNamEvent.jpg", UriKind.Relative))
            .SetEventDetails("A regular in Korea's music scene, Eric has promoted two mini albums and multiple singles in Korea.\nHe has charted at #1 on several occasions and held shows in the U.A.E., Australia, Canada, Malaysia, Morocco, and the United States.")
            .SetLocation("MacEwan Hall (402 Collegiate Blvd NW, Calgary, AB T2N 1N4)")
            .SetStartDate(new DateTime(2021, 09, 05))
            .SetStartTime(2000)
            .SetEndTime(2300)
            .SetFilter(EventFilter.Concert);
        public static EventObject Stampede = new EventObject()
            .SetEventName("Calgary Stampede")
            .SetImage(new Uri("CalgaryStampedeEvent.jpg", UriKind.Relative))
            .SetEventDetails("At the heart of the Calgary Stampede, you’ll find more than 2,500 dedicated volunteers. They embody western values by hosting events across the city, supporting community celebrations and making the Calgary Stampede The Greatest Outdoor Show on Earth. In addition, the Board of Directors are unpaid volunteers who contribute their time to govern the affairs of the Calgary Stampede.")
            .SetLocation("Stampede Grounds (1410 Olympic Way SE, Calgary, AB T2G 2W1)")
            .SetStartDate(new DateTime(2021, 7, 3))
            .SetEndDate(new DateTime(2021, 7, 12))
            .SetStartTime(1100)
            .SetEndTime(2359)
            .SetLinks("https://www.calgarystampede.com/")
            .SetFilter(EventFilter.Special);
        public static EventObject Thriller = new EventObject()
            .SetEventName("Halloween Thriller")
            .SetImage(new Uri("HalloweenEvent.jpg", UriKind.Relative))
            .SetEventDetails("CALGARY'S OFFICIAL HALLOWEEN MEGA PARTY !\n★ CALGARY HALLOWEEN THRILLER 2021 ★\n@ Chakalaka Bar - Sunday October 31st (18+) \nTHE BIGGEST HALLOWEEN PARTY IN CALGARY !\nOFFICIAL MEGA PARTY // SOLD OUT YEARLY\nPRIZES FOR BEST MALE & FEMALE COSTUMES !\nEVERYONE IS WELCOMED ! \n● LIMITED $10.00 TICKETS ARE AVAILABLE\nCLUB ANTHEMS / TOP 40 / HIP HOP / HOUSE / MASHUPS\nProfessional Photographer / Videographer in Attendance\n*** PURCHASE ADVANCE TICKETS FOR GUARANTEED ENTRY ! ***\nPROOF OF VACCINATION NEEDED\n1410 17 AVE SW")
            .SetLocation("Chakalaka (1410 17 Ave SW, Calgary, AB T2T 5S8)")
            .SetStartDate(new DateTime(2021, 10, 04))
            .SetStartTime(2100)
            .SetEndTime(200)
            .SetLinks("https://www.eventbrite.ca/e/calgary-halloween-thriller-2021-sun-oct-31-official-mega-party-tickets-177438101137")
            .SetFilter(EventFilter.Special);
        public static EventObject CalgaryFlames = new EventObject()
            .SetEventName("Calgary Flames Game")
            .SetImage(new Uri("CalgaryFlamesEvent.jpg", UriKind.Relative))
            .SetEventDetails("For almost four decades, the Flames have been electrifying hockey fans in southern Alberta. In that time, not only has the team established itself as a successful NHL franchise, \nbut it has grown into a vital and integral part of our community.\nFrom their on - ice victories and awards to their off - ice charitable endeavours, the Flames have become one of the premier professional sports organizations in North America.")
            .SetLocation("Scotiabank Saddledome (555 Saddledome Rise SE, Calgary, AB T2G 2W1)")
            .SetStartDate(new DateTime(2021, 09, 15))
            .SetStartTime(1900)
            .SetEndTime(2200)
            .SetLinks("https://www.nhl.com/flames")
            .SetFilter(EventFilter.Sport);
        public static EventObject Soccer = new EventObject()
            .SetEventName("CAVS vs PACIFIC")
            .SetImage(new Uri("SoccerEvent.jpg", UriKind.Relative))
            .SetEventDetails("Don't miss this exciting match of Cavalary verus Pacific battle it out!\nCavalry FC is looking to advance to its second Canadian Premier League Final in three years, as it hosts Pacific FC which is searching for its first-ever playoff win.")
            .SetLocation("The Ship & Anchor (534 17 Avenue Southwest Calgary, AB T2S 0B1)")
            .SetStartDate(new DateTime(2021, 09, 19))
            .SetStartTime(1100)
            .SetEndTime(1530)
            .SetLinks("https://www.eventbrite.ca/e/bus-only-nov-20-cavs-vs-pacific-playoff-semi-final-tickets-209446318577?aff=ebdssbdestsearch")
            .SetFilter(EventFilter.Sport);
        public static EventObject Boxing = new EventObject()
            .SetEventName("Boxing Bootcamp")
            .SetImage(new Uri("BoxingEvent.jpg", UriKind.Relative))
            .SetEventDetails("Airswift is passionate about this cause and our goal is to promote cancer research and education and raise funds for various cancer societies around the world.\nThis year in Calgary, Airswift has partnered with Kimani and Martina of Rumble Boxing to host a boot-camp workout.")
            .SetLocation("5149 Country Hills Boulevard Northwest #Unit 310 Calgary, AB T3A 5K8")
            .SetStartDate(new DateTime(2021, 09, 12))
            .SetStartTime(1330)
            .SetEndTime(1430)
            .SetLinks("https://www.eventbrite.ca/e/airswift-rumble-boxing-bootcamp-for-the-canadian-cancer-society-tickets-194081983437?aff=ebdssbdestsearch")
            .SetFilter(EventFilter.Sport);
        public static EventObject WineTasting = new EventObject()
            .SetEventName("Wine Tasting Event")
            .SetImage(new Uri("WineTastingEvent.jpg", UriKind.Relative))
            .SetEventDetails("Join us for a walk-around showcase of the finest Italian wines in current release. This is Calgary's ultimate industry-only tasting.\n50 Italian wineries will be pouring their unique and delicious wines exclusively for members of the trade and media, with an emphasis on wines that combine affordability and excellence, making them ideal choices for by-the-glass programs in restaurants.")
            .SetLocation("The Hudson (at The Guild) (200 8 Avenue Southwest Calgary, AB T2P 1B5)")
            .SetStartDate(new DateTime(2021, 10, 01))
            .SetStartTime(1300)
            .SetEndTime(1700)
            .SetReoccurring(true)
            .SetLinks("https://www.eventbrite.ca/e/gambero-rosso-top-italian-wines-roadshow-calgary-2021-tickets-191839476037?aff=ebdssbdestsearch&keep_tld=1")
            .SetFilter(EventFilter.Food);
        public static EventObject Cocktail = new EventObject()
            .SetEventName("Cocktail Class")
            .SetImage(new Uri("CocktailClassEvent.jpg", UriKind.Relative))
            .SetEventDetails("A cocktail class that goes above and beyond! Tour the distillery, access premium spirits, drink cocktails and gain life-long skills!\nIf you haven't been to Confluence Distilling, this is the ideal way to experience this inner-city craft distillery. Learn from the 10+ years of our cocktail professionals and be immersed in the whole process from conception of the spirit to the tingle of your taste buds.")
            .SetLocation("Confluence Distilling (507 36 Avenue Southeast Calgary, AB T2G 1W5)")
            .SetStartDate(new DateTime(2021, 09, 29))
            .SetStartTime(1700)
            .SetEndTime(2000)
            .SetLinks("https://www.eventbrite.com/e/cocktail-class-at-the-distillery-dec-edition-tickets-193807071167?aff=ebdssbdestsearch")
            .SetFilter(EventFilter.Food);
        public static EventObject ChefsTableDinner = new EventObject()
            .SetEventName("Chef's Table Dinner")
            .SetImage(new Uri("ChefsTableDinnerEvent.jpg", UriKind.Relative))
            .SetEventDetails("Executive chef Christopher Hyde first Chef's Table Dinner at Lina's Italian Mercato. The only, true Italian dinner in Calgary.\nIt's all about the experience. And at Lina's Italian Mercato, you'll feel like you're having dinner in Italy.\nWhen Chef Hyde starts to cook, magic happens. His dishes and recipes are full of flavor and show what true love for cooking really is.")
            .SetLocation("5108 Elbow Drive Southwest Calgary, AB")
            .SetStartDate(new DateTime(2021, 09, 30))
            .SetStartTime(1930)
            .SetEndTime(2200)
            .SetReoccurring(true)
            .SetLinks("https://www.eventbrite.com/e/cocktail-class-at-the-distillery-dec-edition-tickets-193807071167?aff=ebdssbdestsearch")
            .SetFilter(EventFilter.Food);
        public static EventObject WineU = new EventObject()
            .SetEventName("Wine U: Premium Wines!")
            .SetImage(new Uri("WineUEvent.jpg", UriKind.Relative))
            .SetEventDetails("We are popping open premium wines tonight!\nIf you’re thinking about stocking your cellar or need an extra special gift, don’t miss out on this epic night! Join us for our Wine U series as we guide you through a selection of 6 different wines alongside cheese & charcuterie from Soffritto.")
            .SetLocation("4109 University Avenue Northwest Calgary, AB T3B 6K3")
            .SetStartDate(new DateTime(2021, 09, 09))
            .SetStartTime(1830)
            .SetEndTime(2030)
            .SetLinks("https://www.eventbrite.ca/e/wine-u-premium-wines-tickets-211249782787?aff=ebdssbdestsearch")
            .SetFilter(EventFilter.Food);
        public static EventObject Yonex = new EventObject()
            .SetEventName("Yonex Canada Open")
            .SetImage(new Uri("YonexCanadaOpenEvent.jpg", UriKind.Relative))
            .SetEventDetails("Since 2015 the Yonex Canada Open has taken place in Calgary, bringing with it some of the top badminton players in the world. The 2019 event saw 260 competitors from 34 nations, including 5 former world #1 players. With a USD $75,000 prize purse it is the top badminton event in Canada and has found a home at the Markin Macphail Centre at Canada Olympic Park. The competition would not be possible without the people at Badminton Alberta who have made the event into what it is.")
            .SetLocation("Markin Macphail Centre at Canada Olympic Park")
            .SetStartDate(new DateTime(2021, 09, 18))
            .SetStartTime(1630)
            .SetEndTime(1830)
            .SetLinks("https://www.visitcalgary.com/sport-and-culture/success-stories/yonex-canada-open")
            .SetFilter(EventFilter.Sport);
        public static EventObject GlassFusion = new EventObject()
            .SetEventName("Glass Fusion 101")
            .SetImage(new Uri("GlassFusionEvent.jpg", UriKind.Relative))
            .SetEventDetails("Under the gaze of an expert, guests arrange colourful pieces of glass to be fused into bowls, candy dishes, plaques, or vases.\nTurn bits and strips of specialty glass into twinkling kiln-fired treasures! Nothing beats the sparkle of glass. We’ll show you how to create sparkling glass functional artwork! This art form is positively UNIQUE and comes with guaranteed bragging rights! The results are dazzling, and the fun is addictive!")
            .SetLocation("14 St NW, Calgary, AB T2N 1Z7")
            .SetStartDate(new DateTime(2021, 10, 03))
            .SetStartTime(1200)
            .SetEndTime(1400)
            .SetLinks("https://allevents.in/calgary/glass-fusion-101-nov-15th/200021694739624")
            .SetFilter(EventFilter.Special);
        public static EventObject JobFair = new EventObject()
            .SetEventName("Startup Job Fair Online")
            .SetImage(new Uri("JobFairEvent.jpg", UriKind.Relative))
            .SetEventDetails("Exploring new job opportunities? Looking to join a high-growth company? Join our Job Fair Online.\nChat with an actual recruiter or hiring manager. This is not an applicant tracking system. We have representatives from companies that are directly hiring.")
            .SetLocation("Online")
            .SetStartDate(new DateTime(2021, 09, 20))
            .SetStartTime(1000)
            .SetEndTime(1100)
            .SetLinks("https://allevents.in/calgary/glass-fusion-101-nov-15th/200021694739624")
            .SetFilter(EventFilter.Special);
        public static EventObject TimAndTheGloryBoys = new EventObject()
            .SetEventName("Tim & The Glory Boys")
            .SetImage(new Uri("TimAndTheGloryBoysEvent.jpg", UriKind.Relative))
            .SetEventDetails("Been missing Live music? Tim & The Glory Boys bring you a Barn Burnin' Banjo Bash! Don't miss it!\nWith a whole new batch of songs, they are as eager as Canadian beavers to visit your neck o’ the woods. Don’t miss a rare night of live music and fun in your own backyard!")
            .SetLocation("First Alliance Church Calgary (FAC Deerfoot), 12345 40 Street Southeast, Calgary, Canada")
            .SetStartDate(new DateTime(2021, 09, 28))
            .SetStartTime(1900)
            .SetEndTime(2130)
            .SetLinks("https://allevents.in/calgary/tim-and-the-glory-boys-the-home-town-hoedown-tour-calgary-ab/10000165490218699")
            .SetFilter(EventFilter.Special);
    }
}
